using System;
using System.Collections.Generic;

namespace WebAPI_BSC.Models
{
    public partial class StockWorkLiveTable
    {
        public int ShellUserId { get; set; }
        public int ShellOperationId { get; set; }
        public int ShellWorkPageId { get; set; }
        public int ShellWorkPageLineId { get; set; }
        public int ShellMessageId { get; set; }
        public DateTime? ShellDateFrom { get; set; }
        public DateTime? ShellDateTo { get; set; }
        public int? StockLocationId { get; set; }
        public int? StockItemId { get; set; }
        public double StockQuantity { get; set; }
        public double StockQuantity1 { get; set; }
        public double StockQuantity2 { get; set; }
        public double StockQuantity3 { get; set; }
        public double StockQuantity4 { get; set; }
        public double StockQuantity5 { get; set; }
        public double StockQuantity6 { get; set; }
        public double StockQuantity7 { get; set; }
        public double StockQuantity8 { get; set; }
        public double StockQuantity9 { get; set; }
        public double StockAmount { get; set; }
        public double StockAmount1 { get; set; }
        public double StockAmount2 { get; set; }
        public double StockAmount3 { get; set; }
        public double StockAmount4 { get; set; }
        public double StockAmount5 { get; set; }
        public double StockAmount6 { get; set; }
        public double StockAmount7 { get; set; }
        public double StockAmount8 { get; set; }
        public double StockAmount9 { get; set; }
        public DateTime? StockEntryDate { get; set; }
        public int? StockEntryId { get; set; }
        public int? StockEntryLineSortId { get; set; }
        public int? StockEntryTypeId { get; set; }
        public string StockEntryKey { get; set; }
        public string StockEntryName { get; set; }
        public long? StockEntryLineId { get; set; }
        public int? StockEntryLineTypeId { get; set; }
        public int ShellYesNo { get; set; }
        public int ShellYesNo1 { get; set; }
        public int ShellYesNo2 { get; set; }
        public int ShellYesNo3 { get; set; }
        public int ShellYesNo4 { get; set; }
        public int ShellYesNo5 { get; set; }
        public int? ShellWorkPageParentId { get; set; }
        public int? ShellWorkPageLineParentId { get; set; }
        public int? StockCompanyId { get; set; }
        public int? StockCompanyGroupId { get; set; }
        public int? StockItemGroupId { get; set; }
        public int? StockLocationGroupId { get; set; }
        public double Amount { get; set; }
        public double TaxAmount { get; set; }
        public double FullAmount { get; set; }
        public double Price { get; set; }
        public DateTime? StockEntryDate2 { get; set; }
        public int? TaxCodeId { get; set; }
        public double Price1 { get; set; }
        public double Price2 { get; set; }
        public double Price3 { get; set; }
        public double Price4 { get; set; }
        public double Price5 { get; set; }
        public int? StockSalesPriceGroupId { get; set; }
        public int StockEntryCount { get; set; }
        public int? StockEntryParentId { get; set; }
        public long? StockEntryLineParentId { get; set; }
        public double StockPrice { get; set; }
        public double StockPrice1 { get; set; }
        public double FullPrice { get; set; }
        public int? StockUserId { get; set; }
        public int? StockPersonId { get; set; }
        public int? StockCarId { get; set; }
        public int? StockLocationId2 { get; set; }
        public double StockItemNweight { get; set; }
        public double StockItemGweight { get; set; }
        public int? StockEntryStatusId { get; set; }
        public int? StockEntryId2 { get; set; }
        public int? StockPriceId { get; set; }
        public int? TaxCodeId1 { get; set; }
        public int? StockItemId2 { get; set; }
        public int? StockItemId3 { get; set; }
        public int? StockBomplanLineTypeId { get; set; }
        public double Percent1 { get; set; }
        public double Percent2 { get; set; }
        public double Percent3 { get; set; }
        public double Percent4 { get; set; }
        public double Percent5 { get; set; }
        public double Percent { get; set; }
        public int? ShellComputerId { get; set; }
        public int? StockCompanyParentId { get; set; }
        public int? StockEntryProcessId { get; set; }
        public int? StockPayPeriodId { get; set; }
        public int? StockShelfId { get; set; }
        public int? TransPayMethodId { get; set; }
        public TimeSpan? ShellTimeFrom { get; set; }
        public TimeSpan? ShellTimeTo { get; set; }
        public int? StockCostCodeId { get; set; }
        public int? StockSalesUserId { get; set; }
        public int? ShellCreatorUserId { get; set; }
        public DateTime? StockCalculationDate { get; set; }
        public int? StockRecipeItemId { get; set; }
        public double? StockRecipeQuantity { get; set; }
        public double? Fcprice { get; set; }
        public double? StockPurchaseQuantity { get; set; }
        public double? StockPurchaseAmount { get; set; }
        public double? StockWoffQuantity { get; set; }
        public double? StockWoffAmount { get; set; }
        public double? TransPrice { get; set; }
        public double? Quantity { get; set; }
        public int? CompanyId { get; set; }
        public int? TransQuantity { get; set; }
        public string Comment { get; set; }
        public double? StockCompanyCardId { get; set; }
        public int? TransItemId { get; set; }
    }
}
