using System;
using System.Collections.Generic;

namespace WebAPI_BSC.Models
{
    public partial class StockWorkBudgetTable
    {
        public int ShellUserId { get; set; }
        public int ShellOperationId { get; set; }
        public int ShellWorkPageId { get; set; }
        public int ShellWorkPageLineId { get; set; }
        public int ShellMessageId { get; set; }
        public DateTime? ShellDateFrom { get; set; }
        public DateTime? ShellDateTo { get; set; }
        public int? StockCompanyGroupId { get; set; }
        public int? StockCompanyId { get; set; }
        public int? StockLocationGroupId { get; set; }
        public int? StockLocationId { get; set; }
        public int? StockItemGroupId { get; set; }
        public int? StockItemGroupId2 { get; set; }
        public int? StockItemId { get; set; }
        public double StockQuantity { get; set; }
        public int? StockEntryTypeId { get; set; }
        public int? StockEntryLineTypeId { get; set; }
        public double Quantity01 { get; set; }
        public double Quantity02 { get; set; }
        public double Quantity03 { get; set; }
        public double Quantity04 { get; set; }
        public double Quantity05 { get; set; }
        public double Quantity06 { get; set; }
        public double Quantity07 { get; set; }
        public double Quantity08 { get; set; }
        public double Quantity09 { get; set; }
        public double Quantity10 { get; set; }
        public double Quantity11 { get; set; }
        public double Quantity12 { get; set; }
        public double Quantity13 { get; set; }
        public double Quantity14 { get; set; }
        public double Quantity15 { get; set; }
        public double Quantity16 { get; set; }
        public double Quantity17 { get; set; }
        public double Quantity18 { get; set; }
        public double Quantity19 { get; set; }
        public double Quantity20 { get; set; }
        public double Quantity21 { get; set; }
        public double Quantity22 { get; set; }
        public double Quantity23 { get; set; }
        public double Quantity24 { get; set; }
        public double Quantity25 { get; set; }
        public double Quantity26 { get; set; }
        public double Quantity27 { get; set; }
        public double Quantity28 { get; set; }
        public double Quantity29 { get; set; }
        public double Quantity30 { get; set; }
        public double Quantity31 { get; set; }
        public int? ShellWorkPageParentId { get; set; }
        public int? ShellWorkPageLineParentId { get; set; }
        public int? StockBudgetTypeId { get; set; }
        public double QuantityW1 { get; set; }
        public double QuantityW2 { get; set; }
        public double QuantityW3 { get; set; }
        public double QuantityW4 { get; set; }
        public double QuantityW5 { get; set; }
        public double QuantityW6 { get; set; }
        public double QuantityW7 { get; set; }
        public double MinQuantity { get; set; }
        public double MaxQuantity { get; set; }
        public double MinDays { get; set; }
        public double MaxDays { get; set; }
        public double PackQuantity { get; set; }
        public DateTime? StockEntryDate { get; set; }
        public double QuantityW0 { get; set; }
        public double LeftDays { get; set; }
        public int? StockDeliveryGraphId { get; set; }
        public double StockQuantity2 { get; set; }
        public double Quantity32 { get; set; }
        public double Quantity33 { get; set; }
        public double Quantity34 { get; set; }
        public double Quantity35 { get; set; }
        public double Quantity36 { get; set; }
        public double Quantity37 { get; set; }
        public double Quantity38 { get; set; }
        public double Quantity39 { get; set; }
        public double Quantity40 { get; set; }
        public double Quantity41 { get; set; }
        public double Quantity42 { get; set; }
        public int? StockDeliveryTypeId { get; set; }
        public int? StockUsageTypeId { get; set; }
        public int? StockEntryId { get; set; }
        public long? StockEntryLineId { get; set; }
        public double TransQuantity { get; set; }
        public string TransItemUnitKey { get; set; }
        public double TransItemUnitFactor { get; set; }
        public double TransPrice { get; set; }
        public int TransTaxId { get; set; }
        public double TransTaxBaseFactor { get; set; }
        public double TransTaxFactor { get; set; }
        public int? StockLocationId2 { get; set; }
        public double StockQlimitFactor { get; set; }
        public long? StockEntryLineId2 { get; set; }
        public double OrderFactor { get; set; }
    }
}
